apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: spark-operator-edit
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: spark-operator