language: java

services:
  - docker

stages:
  - test
  - test-oc-and-k8s
  - deploy

jobs:
  include:
    - stage: test
      language: java
      env:
        # maven colors
        - MAVEN_OPTS="-Djansi.passthrough=true -Dplexus.logger.type=ansi $MAVEN_OPTS"
      script: make build test

    - stage: test-oc-and-k8s
      env: OPENSHIFT_VERSION=v3.7 BIN=oc
      script:
        - make build
        - ./.travis/.travis.prepare.openshift.sh
        - BIN="oc" ./.travis/.travis.test-oc-and-k8s.sh

    - stage:
      env: OPENSHIFT_VERSION=v3.9 BIN=oc

    - stage:
      env: KUBECTL_VERSION=v1.9.0 MINIKUBE_VERSION=v0.25.2 CHANGE_MINIKUBE_NONE_USER=true BIN=kubectl

    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        # release :latest and :centos-latest
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then make image-publish-all; fi

        # release x.y.z or x.y.z-centos if there is a release
        - ./.travis/.travis.release.images.sh
        - docker logout
