language: java

services:
  - docker

matrix:
  include:
    - env: OPENSHIFT_VERSION=v3.9

before_install:
  - ./.travis/.travis.prepare.sh

script:
  - make test
  - ./.travis/.travis.test-oc.sh

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # release :latest and :centos-latest
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then make image-publish-all; fi

  # release x.y.z or x.y.z-centos if there is a release
  - ./.travis/.travis.release.images.sh
  - docker logout
