language: java

services:
  - docker

script:
  - make test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # release :latest and :centos-latest
  - make image-publish-all

  # release x.y.z or x.y.z-centos if there is a release
  - ./.travis/.travis.release.images.sh
  - docker logout

  # pushes the latest manifests for k8s and OpenShift into 'dist' branch
  - ./.travis/.travis.push.manifests.sh
