apiVersion: v1
kind: ConfigMap
metadata:
  name: my-spark-cluster           # compulsory
  labels:
    radanalytics.io/kind: cluster  # compulsory
data:
  workerNodes: "2"                # optional defaults to 1
  masterNodes: "1"                # optional defaults to 1
#  customImage: ""                 # optional defaults to radanalyticsio/openshift-spark
  
