---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator2
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: spark-operator-edit
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: spark-operator
